class AllDate:
    first_name = "Genrik"
    last_name = "Maleryan"
    email = "g.maleryan@mail.ru"
    mobile = "8999123456"
    month = "March"
    day = "11"
    year = "2000"
    gender = "Male"
    hobbies = "Sports"
    subject = "Maths"
    state = "NCR"
    city = "Delhi"
    address = "Привокальная 3/1"
    result_table_text = "Thanks for submitting the form"
